// <auto-generated />
using System;
using AplikasiSurat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikasiSurat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126080315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AplikasiSurat.Models.SuratKeluar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomorSurat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penerima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalKeluar")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SuratKeluar");
                });

            modelBuilder.Entity("AplikasiSurat.Models.SuratMasuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomorSurat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pengirim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SuratMasuk");
                });
#pragma warning restore 612, 618
        }
    }
}
